version: '3'

services: 
  db-mysql:
    image: mysql:latest
    container_name: "mysql-quotes-db"
    environment:
      MYSQL_USER: "chaitu"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "mysql_quotes"
      MYSQL_PASSWORD: "pwd"
    ports:
      - "3333:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql/data
    healthcheck:
      test: mysql --user=root --password=password -e 'show databases'

#volumes:
#  mysql_data: