version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: "postgres-quotes-db"
    environment:
      POSTGRES_USER: "chaitu"
      POSTGRES_ROOT_PASSWORD: "password"
      POSTGRES_DATABASE: "db"
      POSTGRES_PASSWORD: "pwd"
    ports:
      - "4444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: